remove uneeded code from hooks

diff --git a/usr/local/bin/rocinante b/usr/local/bin/rocinante
--- a/usr/local/bin/rocinante
+++ b/usr/local/bin/rocinante
@@ -111,9 +111,17 @@ if [ -f "${SCRIPTPATH}" ]; then
 
     if [ -n "${PARAMS}" ]; then
         exec "${SH}" "${SCRIPTPATH}" "${PARAMS}"
+        error="$?"
     else
         exec "${SH}" "${SCRIPTPATH}" "$@"
+        error="$?"
     fi
+
+    # Exit on errors
+    if [ "${error}" -ne 0 ]; then
+        error_exit "\n[ERROR]: Failed to execute hook: ${CMD}"
+    fi
+
 else
     error_exit "${SCRIPTPATH} not found."
 fi
